import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WalletProvider } from "@/hooks/useWallet";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "xkira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <WalletProvider>
         {/* <SidebarProvider> */}
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <main className={`${geistSans.className}`}>
            {/* <SidebarTrigger /> */}
              {children}
            </main>
          </ThemeProvider>
         {/* </SidebarProvider> */}
        </WalletProvider>
      </body>
    </html>
  );
}
